### ISSUE TITLE
{"code": 9, "data": {"errorCode": 11, "errorMessage": "", "result": "{\"error\":11,\"desc\":\"Wakeup engine model file invalid\",\"sub_error\":11005}"}, "msg": "唤醒错误"}

### ISSUE THREAD

**Issue by god-zhang** [gdoudeng/react-native-baidu-asr#17]
安卓中:
import { BaiduWakeUp } from 'react-native-baidu-asr';

BaiduWakeUp.init({
            APP_ID: 'xxxxx',
            APP_KEY: 'xxxx',
            SECRET: 'xxxxxx',
        });

        const onWakeUpRes = BaiduWakeUp.addResultListener((e)=>{
            console.log('onWakeUpRes', e)
        })
        const onWakeUpErr = BaiduWakeUp.addErrorListener((e)=>{
            console.log('onWakeUpErr', e)
        })

BaiduWakeUp.start({
                    //表示WakeUp.bin文件定义在assets目录下
                    WP_WORDS_FILE: 'assets:///WakeUp.bin',
                });

初始化报错如下:
{"code": 9, "data": {"errorCode": 11, "errorMessage": "", "result": "{\"error\":11,\"desc\":\"Wakeup engine model file invalid\",\"sub_error\":11005}"}, "msg": "唤醒错误"}

**Comment by god-zhang** [comment]
包名不一致导致的, 已解决

**Comment by gdoudeng** [comment]
好的
