### ISSUE TITLE
唤醒错误  {"code": 9, "data": {"errorCode": 11, "errorMessa ge": "", "result": "{\"error\":11,\"desc\":\"Wakeup engine has no license\",\"sub_error\":11002}"}, "msg": "唤醒错误"}

### ISSUE THREAD

**Issue by shuidaan** [gdoudeng/react-native-baidu-asr#3]
![image](https://user-images.githubusercontent.com/24624971/125555712-0f7b6f6f-2c5a-45a4-afaf-8a0c95b7df5d.png)

 LOG      唤醒错误  {"code": 9, "data": {"errorCode": 11, "errorMessa
ge": "", "result": "{\"error\":11,\"desc\":\"Wakeup engine has no license\",\"sub_error\":11002}"},
"msg": "唤醒错误"}

**Comment by shuidaan** [comment]
正式授权
唤醒词和离线命令词功能需要一个正式授权文件。正式授权由SDK内部管理，无对外接口。正式授权文件在第一次联网使用SDK识别功能下载，比如第一次在线联网使用唤醒词功能或第一次在线识别后，SDK自动下载正式授权文件。正式授权文件有效期为应用新建后的35个月。在最后一个月，SDK一旦发现正式授权文件失效或即将失效，会尝试更新授权文件

注意，appId appKey appSecret包名（applicationId）4个必须完全正确，才能自动下载正式授权文件。

在你的程序包里面是有 applicationId 但是集合到react native 好像就没有这个关键词

**Comment by gdoudeng** [comment]
微信联系过了 是你缺少`auth.properties` 用之前你也没初始化引擎 这issue我关了

**Comment by god-zhang** [comment]
> 微信联系过了 是你缺少`auth.properties` 用之前你也没初始化引擎 这issue我关了

我也出现了这个报错, 这个要怎么设置呀
