### ISSUE TITLE
react-native版本0.7在装完库后运行报错

### ISSUE THREAD

**Issue by caixukunngmn** [gdoudeng/react-native-baidu-asr#5]
Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/env
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

**Comment by gdoudeng** [comment]
emmm 你这个错误不是说你android环境没好吗

**Comment by gdoudeng** [comment]
@caixukunngmn hello 还有问题吗?
