### ISSUE TITLE
语音合成相同的文本会自动缓存么? 缓存后播放就不会触发播放回调函数了

### ISSUE THREAD

**Issue by MajorMayer** [gdoudeng/react-native-baidu-asr#9]
我用语音合成播放了一句话,比如 "你好"
然后我再播放 "你好" 的时候就不会再进行语音合成了 , 对吗 , 因为我没看到又合成回调 , 同时也没有播放回调

能不能始终又播放的回调回来呢 , 这样程序就可以控制现在是否正在播放中 等这些操作了了

**Comment by gdoudeng** [comment]
经过demo测试没复现
